# Cloud Run service configuration
# Deploy with: gcloud run services replace cloud-run.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-business-bot
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'

        # VPC Connector for Cloud SQL and Memorystore
        run.googleapis.com/vpc-access-connector: redis-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only

        # Cloud SQL connection
        run.googleapis.com/cloudsql-instances: PROJECT_ID:us-central1:ai-bot-postgres

        # Execution environment
        run.googleapis.com/execution-environment: gen2

        # CPU allocation
        run.googleapis.com/cpu-throttling: 'false'

    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ai-bot-service-account@PROJECT_ID.iam.gserviceaccount.com

      containers:
      - image: gcr.io/PROJECT_ID/ai-bot:latest

        ports:
        - name: http1
          containerPort: 8080

        resources:
          limits:
            cpu: '1'
            memory: 1Gi

        env:
        # Application config
        - name: ENVIRONMENT
          value: production

        - name: LOG_LEVEL
          value: INFO

        - name: JSON_LOGS
          value: 'true'

        # Database config (Cloud SQL)
        - name: DB_HOST
          value: /cloudsql/PROJECT_ID:us-central1:ai-bot-postgres

        - name: DB_PORT
          value: '5432'

        - name: DB_NAME
          value: ai_bot_db

        - name: DB_USER
          value: ai_bot_user

        # Redis config (Memorystore)
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-url
              key: latest

        # API keys (from Secret Manager)
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-token
              key: latest

        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest

        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest

        # Google Cloud config
        - name: GOOGLE_CLOUD_PROJECT
          value: PROJECT_ID

        - name: DOCUMENT_AI_PROCESSOR_ID
          valueFrom:
            secretKeyRef:
              name: document-ai-processor-id
              key: latest

        # API config
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret-key
              key: latest

        - name: ALLOWED_ORIGINS
          value: https://yourdomain.com,https://app.yourdomain.com

        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
